#!/bin/bash

NAME="gif1"
INTERNAL_IP="$(ifconfig en0 | grep "inet " | tr -s " " | cut -d " " -f 2)"

echo -n "please enter your SERVER_IPv4_ADDRESS: "
read -a SERVER_IPv4_ADDRESS

echo -n "please enter your SERVER_IPv6_ADDRESS: "
read -a SERVER_IPv6_ADDRESS

sudo ifconfig "$NAME" create
sudo ifconfig "$NAME" tunnel "$INTERNAL_IP" "$SERVER_IPv4_ADDRESS"
sudo ifconfig "$NAME" inet6 "${SERVER_IPv6_ADDRESS%%${SERVER_IPv6_ADDRESS: -1}}2" "$SERVER_IPv6_ADDRESS" prefixlen 128
sudo route -n add -inet6 default "$SERVER_IPv6_ADDRESS"

echo ""
echo "your tunnel has been created as: $NAME"
echo "you can delete your tunnel by typing: sudo ifconfig $NAME destroy"

echo ""
echo "now attempting to ping the ipv6 internet, ^C to stop"
ping6 ipv6.google.com
